version: '3.9'

services:
  app:
    image: ghcr.io/agnaistic/agnaistic:latest
    networks:
      storage_swarm:
        aliases:
          - agnaistic
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 3
      placement:
        constraints:
          - "node.role!=manager"
    ports:
      - '3001:3001'
    volumes:
      - agn-data:/app/db
      - agn-assets:/app/dist/assets
    environment:
      LOG_LEVEL: info
      DB_NAME: agnai
      DB_HOST: /run/secrets/db_host
      DB_PORT: 27017
      NODE_ENV: production
      JWT_SECRET: /run/secrets/jwt_secret
      JWT_EXPIRY: '30d'
      REDIS_HOST: /run/secrets/redis_host
      REDIS_PORT: 6379
      HORDE_WAIT_SECS: 150
      ADAPTERS: horde,novel,kobold,openai,scale,claude,goose
      USE_S3: 'true'
      AWS_ACCESS_KEY_ID: /run/secrets/aws_id
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws_secret
      BUCKET_NAME: /run/secrets/bucket_name
      BUCKET_ENDPOINT: /run/secrets/bucket_endpoint
      PATREON: 'true'
    secrets:
      - jwt_secret
      - aws_id
      - aws_secret
      - bucket_name
      - bucket_endpoint
      - db_host
      - redis_host

networks:
  storage_swarm:
    external: true

secrets:
  jwt_secret:
    external: true
  aws_id:
    external: true
  aws_secret:
    external: true
  bucket_name:
    external: true
  bucket_endpoint:
    external: true
  db_host:
    external: true
  redis_host:
    external: true

volumes:
  agn-data:
  agn-assets:
