version: '2'

services:
  app:
    image: ghcr.io/luminai-companion/agnaistic:latest
    restart: always
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=agnai
      - INITIAL_USER=admin
      - INITIAL_PASSWORD=password
      - JWT_SECRET=self-hosting
    
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'