name: Publish API
on:
  push:
    branches: ['dev']

env:
  node-version: '18.4.0'
  pnpm-version: 7.2.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node and PNPM
        uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{  env.node-version  }}
          pnpm-version: ${{  env.pnpm-version  }}

      - name: Install API dependencies
        run: |
          pnpm install --frozen-lockfile --prod

      - name: Build
        run: |
          pnpm run build:server

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'api.zip'
          exclusions: '*.git* *.vscode* .editorconfig web/*'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'api.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
