name: Deploy to DEV

on: workflow_dispatch

permissions:
  contents: read

env:
  IMAGE_NAME: agnaistic
  node-version: '18.4.0'
  pnpm-version: 8.6.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node and PNPM
        uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{  env.node-version  }}
          pnpm-version: ${{  env.pnpm-version  }}

      - name: Get cached dependencies
        # cache is automatically saved after this job completes. jobs depending on this one will get the latest cached files
        id: cache-step
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install project dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
          ls -la
          echo $NODE_ENV
          pnpm install --frozen-lockfile

      - name: Build frontend
        env:
          INJECT_SCRIPT: ${{ secrets.INJECT_SCRIPT }}
        run: |
          pnpm run build:server
          pnpm run build:prod
          cp dist/index.html dist/original.html
          node .github/inject.js

      - name: Publish to DEV
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.S3_ASSET_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_ASSET_SECRET_KEY }}
          space_name: ${{ secrets.S3_DEV_ASSET_BUCKET }}
          space_region: ${{ secrets.S3_ASSET_REGION }}
          permission: public-read
          source: dist

      # - name: Build image
      #   run: |
      #     docker build -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:dev --build-arg SHA=$GITHUB_SHA .
      #     docker tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:dev ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$GITHUB_SHA

      # - name: Log in to Container Registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      # - name: Publish
      #   run: |
      #     docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:dev
      #     docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$GITHUB_SHA

      # - name: Update Service
      #   run: |
      #     sh .github/dev-deploy.sh ${{ secrets.SSH_SERVER }}
