name: Publish NPM Package

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.4.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '8.6.0'

      - name: Get cached dependencies
        # cache is automatically saved after this job completes. jobs depending on this one will get the latest cached files
        id: cache-step
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
          echo $NODE_ENV
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          echo $NODE_ENV
          pnpm build:prod

      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish
